recruitment/candidates/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path(
        route='new/',
        view=views.new_view,
        name='new_candidate'
    ),
    path(
        route='new_experience/',
        view=views.new_experience_view,
        name='new_experience',
    ),
     path(
        route='detail/<int:cedula>',
        view=views.detail_view,
        name='detail',
    ),
    path(
        route='login/',
        view=views.login_view,
        name='login',
    )
]

recruitment/recruitment/urls.py
from django.contrib import admin

from django.urls import path, include

from django.conf import settings

from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
      path(
        route='',
        view=views.home,
        name='home'
    ),
    path('candidates/', include(('candidates.urls', 'candidates'), namespace='candidates')),
    path('rh/', include(('human_resources.urls', 'rh'), namespace='rh')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recruitment/candidates/models.py
from django.db import models

from django.contrib.auth.models import User

from .validators import validar_cedula

from human_resources.models import (
  Puesto,
  Competencia,
  Capacitacion,
  Empleado,
)


class Experiencia(models.Model):
  empresa = models.CharField(max_length=100)
  puesto_ocupado = models.ForeignKey(Puesto, on_delete=models.CASCADE)
  fecha_desde = models.DateField()
  fecha_hasta = models.DateField()
  salario = models.IntegerField()

  def __str__(self):
    return self.puesto_ocupado.nombre


class Candidato(models.Model):
  cedula = models.CharField(max_length=11, validators=[validar_cedula])
  nombre = models.CharField(max_length=100)
  puesto = models.ForeignKey(Puesto, on_delete=models.CASCADE)
  departamento = models.CharField(max_length=100)
  salario_aspira = models.IntegerField(blank=True)
  competencias = models.ManyToManyField(Competencia, blank=True)
  capacitaciones = models.ManyToManyField(Capacitacion, blank=True)
  experiencias = models.ManyToManyField(Experiencia, blank=True)
  recomendado_por = models.ForeignKey(Empleado,  on_delete=models.CASCADE, null=True, blank=True)
  esta_reclutado = models.BooleanField(null=True, blank=True, default=False)

  def __str__(self):
    return self.nombre

recruitment/candidates/forms.py
from django import forms

from .models import Candidato, Experiencia


class CandidateForm(forms.ModelForm):
    class Meta:
        model = Candidato
        fields = (
            'cedula',
            'nombre',
            'puesto',
            'departamento',
            'salario_aspira',
            'competencias',
            'capacitaciones',
            'experiencias',
            'recomendado_por',
        )


class ExperienciaForm(forms.ModelForm):
    class Meta:
        model = Experiencia
        fields = (
            'empresa',
            'puesto_ocupado',
            'fecha_desde',
            'fecha_hasta',
            'salario',
        )

recruitment/candidates/views.py
from django.shortcuts import render, redirect

from .models import Candidato

from human_resources.models import Puesto

from .forms import CandidateForm, ExperienciaForm

def new_view(request):
    if request.method == 'POST':
        form = CandidateForm(request.POST)

        if (form.is_valid()):
            form.save()
        else:
            form = CandidateForm(request.POST)
            context = { 'form': form, 'error': 'Cedula invalida'}
            return render(request, 'new.html', context)

        return redirect('home')

    form = CandidateForm()
    context = { 'form': form }

    return render(request, 'new.html', context)


def new_experience_view(request):
    if request.method == 'POST':
        form = ExperienciaForm(request.POST)

        if (form.is_valid()):
            form.save()
        else:
            form = ExperienciaForm(request.POST)
            return render(request, 'new_experience.html', {})

    form = ExperienciaForm()
    context = { 'form': form }

    return render(request, 'new_experience.html', context)


def login_view(request):
    if request.method == 'POST':
        cedula = request.POST['cedula']
        return redirect(f'/candidates/detail/{cedula}')

    return render(request, 'candidates_login.html', {})


def detail_view(request, cedula):        
    if request.method == 'POST':
        try:
            candidato = Candidato.objects.get(cedula=request.POST['cedula'])

            form = CandidateForm(request.POST, instance=candidato)

            form.save()

            return render(request, 'candidates_detail.html', { 'candidato': candidato, 'form': form })

        except Candidato.DoesNotExist:
            return redirect('candidates:login')    

    
    try:
        candidato = Candidato.objects.get(cedula=cedula)
    except Candidato.DoesNotExist:
        return redirect('candidates:login')    

    form = CandidateForm(instance=candidato)

    return render(request, 'candidates_detail.html', { 'candidato': candidato, 'form': form })

recruitment/candidates/templates/candidates_detail.html
{% extends 'base.html' %}

{% block container %}
    <a href="{% url 'candidates:new_experience' %}" class="btn btn-primary">Crear nueva experiencia laboral</a>

    <form method="post" style="margin-top: 2em">
	{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Save</button>
  </form>
{% endblock container %}

recruitment/candidates/templates/candidates_login.html
{% extends 'base.html' %}

{% block container %}
  <h1 style="margin-bottom: 50px">Login</h1>
  {% if error %}
    <div class="alert alert-danger" role="alert">
      {{ error }}
    </div>
  {% endif %}
  <form action="{% url 'candidates:login' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="exampleInputEmail1">Cedula</label>
      <input name="cedula" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Cedula">
    </div>
    <button type="submit" class="btn btn-success">Login</button>
  </form>
{% endblock container %}

recruitment/candidates/templates/new.html
{% extends 'base.html' %}

{% block container %}
  <h1 style="margin-bottom: 50px">Solicitud para candidatos</h1>  
  <form method="post" novalidate>
	{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Save person</button>
  </form>
{% endblock container %}

recruitment/candidates/templates/new_experience.html
{% extends 'base.html' %}

{% block container %}
  <h1 style="margin-bottom: 50px">Agregar experiencia</h1>  
  <form method="post">
	{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Save person</button>
  </form>
{% endblock container %}