recruitment/candidates/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path(
        route='new/',
        view=views.new_view,
        name='new_candidate'
    ),
    path(
        route='new_experience/',
        view=views.new_experience_view,
        name='new_experience',
    ),
     path(
        route='detail/<int:cedula>',
        view=views.detail_view,
        name='detail',
    ),
    path(
        route='login/',
        view=views.login_view,
        name='login',
    )
]

recruitment/recruitment/urls.py
from django.contrib import admin

from django.urls import path, include

from django.conf import settings

from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
      path(
        route='',
        view=views.home,
        name='home'
    ),
    path('candidates/', include(('candidates.urls', 'candidates'), namespace='candidates')),
    path('rh/', include(('human_resources.urls', 'rh'), namespace='rh')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recruitment/templates/home/index.html
{% extends 'base/base.html' %}

{% block head_content %}
  <style>
    .home {
      justify-content: center;
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }
  </style>
{% endblock head_content %}

{% block container %}
  <div class="home">
    <div class="row">
      <div class="col-3 offset-2">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">Candidatos</h5>
            <p class="card-text">App para que los candidatos hagan su solicitud.</p>
            <a href="{% url 'candidates:new_candidate' %}" class="">Crear solicitud</a> <br />
            <a href="{% url 'candidates:login' %}" class="">Ver mi solicitud</a>
          </div>
        </div>
      </div>
      <div class="col-3 offset-1">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">Recursos Humanos</h5>
            <p class="card-text">App para el area de Recursos Humanos.</p>
            <a href="{% url 'rh:login' %}" class="btn btn-primary">Go</a>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock container %}