recruitment/candidates/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path(
        route='new/',
        view=views.new_view,
        name='new_candidate'
    ),
    path(
        route='new_experience/',
        view=views.new_experience_view,
        name='new_experience',
    ),
     path(
        route='detail/<int:cedula>',
        view=views.detail_view,
        name='detail',
    ),
    path(
        route='login/',
        view=views.login_view,
        name='login',
    )
]

recruitment/human_resources/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path(
        route='login/',
        view=views.login_view,
        name='login'
    ),
    path(
        route='logout/',
        view=views.logout_view,
        name='logout'
    ),

    path(
        route='home/',
        view=views.home_view,
        name='home'
    ),
    path(
        route='reclutar/<int:id>/',
        view=views.reclutar_view,
        name='reclutar'
    ),
    path('report/', views.Pdf.as_view(), name="report")

]

recruitment/recruitment/urls.py
from django.contrib import admin

from django.urls import path, include

from django.conf import settings

from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
      path(
        route='',
        view=views.home,
        name='home'
    ),
    path('candidates/', include(('candidates.urls', 'candidates'), namespace='candidates')),
    path('rh/', include(('human_resources.urls', 'rh'), namespace='rh')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recruitment/human_resources/models.py
from django.db import models

from django.contrib.auth.models import User

from .validators import validar_cedula

# Create your models here.
class Competencia(models.Model):
  description = models.CharField(max_length=100)
  estado = models.BooleanField(default=True)

  def __str__(self):
    return self.description


class Idioma(models.Model):
  nombre = models.CharField(max_length=100)
  estado = models.BooleanField(default=True)

  def __str__(self):
    return self.nombre


class Capacitacion(models.Model):
  NIVELES = (
    ('Grado', 'Grado'),
    ('Post Grado', 'Post Grado'),
    ('Maestría', 'Maestría'),
    ('Doctorado', 'Doctorado'),
    ('Técnico', 'Técnico'),
    ('Gestión', 'Gestión'),
  )

  descripcion = models.CharField(max_length=100)
  nivel = models.CharField(max_length=100, choices=NIVELES)
  fecha_desde = models.DateField()
  fecha_hasta = models.DateField()
  institucion = models.CharField(max_length=100)
  estado = models.BooleanField(default=True)

  def __str__(self):
    return self.descripcion


class Puesto(models.Model):
  NIVELES = (
    ('Alto', 'Alto'),
    ('Medio', 'Medio'),
    ('Bajo', 'Bajo'),
  )

  nombre = models.CharField(max_length=100)
  nivel_riesgo = models.CharField(max_length=100, choices=NIVELES)
  nivel_minimo_salario = models.IntegerField()
  nivel_maximo_salario = models.IntegerField()
  estado = models.BooleanField(default=True)

  def __str__(self):
    return self.nombre


class Empleado(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
  cedula = models.CharField(max_length=11, validators=[validar_cedula])
  nombre = models.CharField(max_length=100)
  fecha_ingreso = models.DateField(auto_now=True, null=True, blank=True)
  departamento = models.CharField(max_length=100)
  puesto = models.ForeignKey('Puesto',  on_delete=models.CASCADE, null=True, blank=True)
  salario_mensual = models.IntegerField(blank=True, null=True)
  estado = models.BooleanField(default=True, null=True, blank=True)

  def __str__(self):
    return self.nombre

recruitment/human_resources/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse, FileResponse

from django.contrib.auth import authenticate, logout, login

from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required

from candidates.models import Candidato

from .models import Empleado

from io import BytesIO

from django.template.loader import get_template

import xhtml2pdf.pisa as pisa

from django.views.generic import View

from django.utils import timezone

class Render:

    @staticmethod
    def render(path: str, params: dict):
        template = get_template(path)
        html = template.render(params)
        response = BytesIO()
        pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), response)
        if not pdf.err:
            http_response = HttpResponse(response.getvalue(), content_type='application/pdf')
            http_response['Content-Disposition'] = 'attachment;filename=report_file.pdf'
            return http_response
        else:
            return HttpResponse("Error Rendering PDF", status=400)



class Pdf(View):

    def get(self, request):
        candidatos = Candidato.objects.all()
        today = timezone.now()
        params = {
            'today': today,
            'candidatos': candidatos,
            'request': request,
            'is_report': True
        }
    
        return Render.render('report.html', params)

        

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('rh:home')

        return render(request, 'login.html', {'error': 'incorrect username or password'})

    return render(request, 'login.html')

@login_required
def logout_view(request):
    logout(request)
    return redirect('rh:login')


@login_required
def home_view(request):
    candidatos = Candidato.objects.all()
    return render(request, 'home.html', { 'candidatos': candidatos })


@login_required
def reclutar_view(request, id):
    candidato = Candidato.objects.get(pk=id)

    candidato.esta_reclutado = True

    candidato.save()
    
    user = User.objects.create_user(
        username=candidato.cedula,
        password=candidato.cedula,
    )

    Empleado.objects.create(
        user=user,
        cedula=candidato.cedula,
        nombre=candidato.nombre,
        departamento=candidato.departamento
    )


    return redirect('rh:home')

recruitment/human_resources/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>

<body>
    {% if is_report != True %}
        <nav class="navbar fixed-top navbar-light bg-light">
            <a class="navbar-brand">Hi {{ user }}</a>
            {% if user.first_name %}
                <a class="" href="/admin">Admin Site</a>
                <a class="" href="{% url 'rh:logout' %}">Logout</a>
            {% else %}
                <a class="" href="{% url 'home' %}">Go home</a>
            {% endif %}
        </nav>
    {% endif %}


    <div class="container" style="margin-top: 5em">
        {% block container %}
        {% endblock%}
    </div>
</body>

</html>

recruitment/human_resources/templates/home.html
{% extends 'base.html' %}

{% block container %}
<a href="{% url 'rh:report' %}" target="_blank" class="btn btn-primary">Generar reporte</a>

<h1 style="margin-bottom: 50px">Lista de candidatos</h1>

<ul class="list-group">
  {% for candidato in candidatos %}
  <li class="list-group-item">
    <strong>{{ candidato.nombre }}</strong>
    {% if is_report != True %}
      {% if candidato.esta_reclutado %}
        <a style="float:right">Esta reclutado</a>
      {% else %}
        <a href="{% url 'rh:reclutar' id=candidato.id %}" style="float:right">Reclutar</a>
      {% endif %}
    {% endif %}

  </li>
  <li class="list-group-item" style="margin-bottom: 3em">
    <ul class="list-group">
      <li class="list-group-item">
        <strong>Cedula: </strong>
        {{ candidato.cedula }}
      </li>
      <li class="list-group-item">
        <strong>Puesto que aspira: </strong>
        {{ candidato.puesto }}
      </li>
      <li class="list-group-item">
        <strong>Departamento: </strong>
        {{ candidato.departamento }}
      </li>
      <li class="list-group-item">
        <strong>Salario que aspira: </strong>
        RD${{ candidato.salario_aspira }}
      </li>
      <li class="list-group-item">
        <strong>Competencias: </strong>
        <ul class="">
          {% for competencia in candidato.competencias.all %}
          <li class="">
            {{ competencia.description }}
          </li>
          {% endfor %}
        </ul>
      </li>
      <li class="list-group-item">
        <strong>Capacitaciones: </strong>
        <ul class="">
          {% for capacitacion in candidato.capacitaciones.all %}
          <li class="">
            <span class="">
              {{ capacitacion.descripcion }} |
            </span>
            <span class="">
              {{ capacitacion.nivel }} |
            </span>
            <span class="">
              {{ capacitacion.fecha_desde }} |
            </span>
            <span class="">
              {{ capacitacion.fecha_hasta }} |
            </span>
            <span class="">
              {{ capacitacion.institucion }}
            </span>
          </li>
          {% endfor %}
        </ul>
      </li>
      <li class="list-group-item">
        <strong>Experiencias: </strong>
        <ul class="">
          {% for experiencia in candidato.experiencias.all %}
          <li class="">
            {{ experiencia.empresa }}
          </li>
          <li class="">
            {{ experiencia.fecha_desde }}
          </li>
          <li class="">
            {{ experiencia.fecha_hasta }}
          </li>
          <li class="">
            RD${{ experiencia.salario }}
          </li>
          {% endfor %}
        </ul>
      </li>
      <li class="list-group-item">
        <strong>Recomendado por: </strong>
        {{ candidato.recomendado_por }}
      </li>
    </ul>
  </li>
  {% endfor %}
</ul>


{% endblock container %}

recruitment/human_resources/templates/login.html
{% extends 'base.html' %}

{% block container %}
  <h1 style="margin-bottom: 50px">Login</h1>
  {% if error %}
    <div class="alert alert-danger" role="alert">
      {{ error }}
    </div>
  {% endif %}
  <form action="{% url 'rh:login' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="exampleInputEmail1">Username</label>
      <input name="username" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Username">
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-success">Save person</button>
  </form>
{% endblock container %}

recruitment/human_resources/templates/report.html
{% extends 'base.html' %}

{% block container %}
<h1 style="margin-bottom: 50px">Lista de candidatos</h1>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Cédula</th>
            <th>Aspiración Salarial</th>
        </tr>
    </thead>
    <tbody>
        {% for candidato in candidatos %}
        <tr>
            <th>{{candidato.id}}</th>
            <td>{{ candidato.cedula }}</td>
            <td>{{ candidato.nombre }}</td>
            <td>{{ candidato.salario_aspira }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock container %}